import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from 'react-router'
import { supabase } from '@/utils/supabase'
import { useAuth } from './use-auth'
import type { CreatePollInput } from '@/utils/validators'
import type { TablesInsert } from '@/utils/types'

export function useCreatePoll() {
	const { user } = useAuth()
	const queryClient = useQueryClient()
	const navigate = useNavigate()

	return useMutation({
		mutationFn: async (input: CreatePollInput) => {
			// Allow anonymous poll creation - user is optional
			// Insert poll
			const pollData: TablesInsert<'polls'> = {
				slug: '', // Will be auto-generated by trigger
				creator_id: user?.id || null,
				title: input.title,
				description: input.description || null,
				type: input.type,
				visibility: input.visibility,
				show_results_before_vote: input.showResultsBeforeVote,
				require_auth_to_vote: input.requireAuthToVote,
				allow_embed: input.allowEmbed,
				max_selections: input.type === 'multiple' ? input.maxSelections : null,
				closes_at: input.closesAt ? input.closesAt.toISOString() : null,
			}

			const { data: poll, error: pollError } = await supabase
				.from('polls')
				.insert(pollData)
				.select()
				.single()

			if (pollError) throw pollError

			// Insert options
			const optionsData = input.options.map((option, index) => ({
				poll_id: poll.id,
				label: option.label,
				position: index,
			}))

			const { error: optionsError } = await supabase
				.from('poll_options')
				.insert(optionsData)

			if (optionsError) throw optionsError

			return poll
		},
		onSuccess: (poll) => {
			queryClient.invalidateQueries({ queryKey: ['polls'] })
			navigate(`/poll/${poll.slug}`)
		},
	})
}
